name: httpserver
description: A sample application
homepage: https://www.dartlang.org/docs/tutorials/httpserver/
dependencies:
  http_server: ^0.9.2
  http: any
  crypto: any
  polymer: ">=0.15.2 <0.17.0"
  core_elements: ">=0.7.0 <0.8.0"
  paper_elements: ">=0.7.0 <0.8.0"
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- polymer:
    entry_points:
    inline_stylesheets:
      lib/src/paper-shadow/paper-shadow.css: false
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
